name: Bump Version and Deploy
on:
  push:
    branches:
      - master
jobs:
  bump-version-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4.2
        with:
          github_token: ${{ secrets.bump_version }}
          default_bump: false
